In [1]:
import cv2
import numpy as np
import PIL as Image

In [10]:
def draw_min_rect_rectangle(mask_path):
    image = cv2.imread(mask_path)
    print(image.shape)
    thresh = cv2.Canny(image, 128, 256)
 
    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    img = np.copy(image)
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        # 绘制矩形
        cv2.rectangle(img,  (x, y+h), (x+w, y), (255,255,255),-1)
        # cv2.rectangle(img,  (x, y+h), (x+w, y), (255),-1)

         # 将最小内接矩形填充为白色
    gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # 如果array已经是灰度数据，则不需要转换
    print(img.shape)
    print(type(img))
    cv2.imwrite('z23213.png',img)

In [11]:
draw_min_rect_rectangle('TTTTEST.png')

(532, 545, 3)
(532, 545, 3)
<class 'numpy.ndarray'>


In [82]:
image = cv2.imread('z23213.png')
print(type(image))
print(image.max())
print(image.min())
target = torch.from_numpy(image)


<class 'numpy.ndarray'>
255
0


In [80]:
index1 = torch.argmax(target)
index2 = torch.argmin(target)
print(target.view(-1)[index1])
print(target.view(-1)[index2])

tensor(255, dtype=torch.uint8)
tensor(0, dtype=torch.uint8)


In [ ]:
def valid_pred_process(pred, threshold):
    pred = torch.sigmoid(pred)
    pred[pred < Threshold] = 0
    pred[pred >= Threshold] = 255
    # pred = cv2.cvtColor(pred, cv2.COLOR_BGR2GRAY)  # 转换为灰度图像
    thresh = cv2.Canny(pred, 128, 256)
    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    # img = np.copy(image)
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        # 绘制矩形
        cv2.rectangle(pred,  (x, y+h), (x+w, y), (255,255,255),-1)
         # 将最小内接矩形填充为白色
    gray_image = cv2.cvtColor(pred, cv2.COLOR_BGR2GRAY)  # 如果array已经是灰度数据，则不需要转换
    return gray_image

In [10]:
import torch
 
a = torch.randn(1, 3)
aa = torch.mean(a)
print(a)
print(aa)

tensor([[0.1008, 0.7593, 0.1166]])
tensor(0.3255)


In [107]:
import torch
 
# 创建一个二维tensor
x = torch.tensor([[1,2,3],[4,5,6]],dtype = torch.float) 

# 对所有元素进行求和
sum_all = torch.mean(x[x>=4])
 
print(sum_all)  # 输出: tensor(10)

tensor(5.)


In [136]:
import numpy as np
from scipy.spatial.distance import cityblock, chebyshev
from scipy.stats import pearsonr

# 生成两个随机二维数组
array1 = np.array([[1, 1, 1, 1],[1, 1, 1, 1]])
array2 = np.array([[1, 1, 0, 0],[1, 1, 1, 0]])
# 余弦相似度
cosine_similarity = np.dot(array1.flatten(), array2.flatten()) / (np.linalg.norm(array1) * np.linalg.norm(array2))

euclidean_distance = np.linalg.norm(array1 - array2)

# 曼哈顿距离
manhattan_distance = cityblock(array1.flatten(), array2.flatten())

# 切比雪夫距离
chebyshev_distance = chebyshev(array1.flatten(), array2.flatten())

# 杰卡德相似系数
jaccard_similarity = len(np.intersect1d(array1, array2)) / len(np.union1d(array1, array2))

# 皮尔逊相关系数
array1_flattened = array1.flatten()
array2_flattened = array2.flatten()
pearson_correlation, _ = pearsonr(array1_flattened, array2_flattened)

# 输出结果
print("数组1:")
print(array1)
print("数组2:")
print(array2)
print("余弦相似度:", cosine_similarity)
print("欧式距离:", euclidean_distance)
print("曼哈顿距离:", manhattan_distance)
print("切比雪夫距离:", chebyshev_distance)
print("杰卡德相似系数:", jaccard_similarity)
print("皮尔逊相关系数:", pearson_correlation)
print(array1*0.3)

数组1:
[[1 1 1 1]
 [1 1 1 1]]
数组2:
[[1 1 0 0]
 [1 1 1 0]]
余弦相似度: 0.7905694150420948
欧式距离: 1.7320508075688772
曼哈顿距离: 3
切比雪夫距离: 1
杰卡德相似系数: 0.5
皮尔逊相关系数: nan
[[0.3 0.3 0.3 0.3]
 [0.3 0.3 0.3 0.3]]


In [138]:
5/2

2.5

In [139]:
def get_last_position(text, symbol):
    return text.rfind(symbol)
 
text = "example.com?param=1&param=2&"
symbol = "&"
last_position = get_last_position(text, symbol)
print(f"The last position of '{symbol}' is: {last_position}")

The last position of '&' is: 27
